### ISSUE TITLE
Base32 decode by CodecPolicy.STRICT

### ISSUE THREAD

**Issue by TLZS-zhangxueqiang** [Roboh97/totp-kt#8]
Hi buddy
I want to check an input string to see if it is a valid Base32 string. 
How can I do that? 
Base32 decoding can be achieved by specifying CodecPolicy.STRICT. 
How do I pass CodecPolicy.STRICT to the Base32 library?

**Comment by robinohs** [comment]
Hello!
Which input string do you mean?
Do you want to validate a secret that is passed to e.g. generateHash?
